<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assignment3" nsURI="http://www.sales.refactored.org/assignment3"
    nsPrefix="assignment3">
  <eClassifiers xsi:type="ecore:EClass" name="Company">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tradeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stock" upperBound="-1"
        eType="#//Stock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cashSales" upperBound="-1"
        eType="#//CashSales" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creditSales" upperBound="-1"
        eType="#//CreditSales" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" upperBound="-1" eType="#//Item"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unitAmount" eType="#//Price"
        containment="true" eOpposite="#//Price/item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineItems" lowerBound="1"
        upperBound="-1" eType="#//LineItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="total" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1" eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CashSales" eSuperTypes="#//Transaction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreditSales" eSuperTypes="#//Transaction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Price">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sellingPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//Item" eOpposite="#//Item/unitAmount"/>
  </eClassifiers>
</ecore:EPackage>
